init:
  - prerelease.bat
version: 1.0.{build}

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}$(PRERELEASE)'

build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: minimal

deploy:
  # Deploying to NuGet feed
  - provider: NuGet
    api_key:
      secure: FtEm5cB4Y8e/+IshAAD19yRnxMX++DWrHeB3kUWu9KTl7KlGp1OYBuXtV6vs4PZD
    skip_symbols: false
    artifact: /.*\.nupkg/